# -*- coding: utf-8 -*-
"""lambda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/136-UGyBqMY-N_LRc_V-dEBXwr18iToET
"""

a = ["Ivan Petrov 14", "grigori avramov 52", "Alina Olegovna 22", "Natalia Maximovna 54"]
x = sorted(a, key = lambda x: int(x[-2]))
print(x)