# -*- coding: utf-8 -*-
"""min4.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12UkkxWRUoa1WoZixnUK82t3ZhmJdDikQ
"""

a = int(input())
b = int(input())
c = int(input())
d = int(input())
def min4(a,b,c,d):
  x = min(a,b,c,d)
  return(x)
print(min4(a,b,c,d))