# -*- coding: utf-8 -*-
"""my_div(n).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wYarRu7qgGLa6orsSk6zs-1O8TfKuBfm
"""

n = int(input())
def my_div(n):
  i = 1
  while i < n-1:
    if n % i == 0:
      x = i
    i = i + 1
  return(x)
print(my_div(n))