# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/136-UGyBqMY-N_LRc_V-dEBXwr18iToET
"""

a = int(input())
n = int(input())
def Power(b, a, n):
    b = b * a
    n = n - 1
    if n == 1:
        print(b)
        return
    Power(b, a, n)
print(Power(a, a, n))